apiVersion: apps/v1
kind: Deployment
metadata:
  name: ristorantedevicenzo-development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ristorantedevicenzo
  template:
    metadata:
      labels:
        app: ristorantedevicenzo
    spec:
      containers:
        - name: ristorantedevicenzo
          image: itsjipa/ristorantedevicenzo:main
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
              
---
apiVersion: v1
kind: Service
metadata:
  name: ristorantedevicenzo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ristorantedevicenzo
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ristorantedevicenzo-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ristorantedevicenzo
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
